---
global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: solo-pool
    dns_sd_configs:
      - names: ['solo-pool']
        type: A
        port: 8000

  - job_name: node
    dns_sd_configs:
      - names: ['node-exporter']
        type: A
        port: 9100
