{
 "title": "Solo Pool",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Estimated Hashrate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(stratum_hashes_total[5m]))"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stratum_connections_count" }
   ]
  },
  {
   "title": "Valid Shares Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Shares" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(stratum_shares_total{valid=\"true\"}[1d])",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "Invalid Shares Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Shares" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(stratum_shares_total{valid=\"false\"}[1d])",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "Blocks Found This Month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(stratum_blocks_found[4w])"
    }
   ]
  },
  {
   "title": "Historical Hashrate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stratum_hashes_total[5m]))"
    }
   ]
  },
  {
   "title": "Historical Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(stratum_connections_count)" }
   ]
  }
 ]
}